#!/bin/bash
rsync -rvzc --delete \
      --exclude="/CNAME" \
      --exclude="/README.md" \
      --exclude="/.gitignore" \
      --exclude="/.git" \
      --exclude="/.nojekyll" \
      --exclude="/src" \
      out/ ..
git add ..
git reset -- src/
git commit -m "Update static website"
